version: 2.1

# https://circleci.com/docs/reusing-config#using-the-parameters-declaration
commands: # a reusable commands with parameters 

  docker-build-push:
    parameters:
      dir:
        default: "."
        type: string
      tag:
        default: "latest"
        type: string
      image:
        type: string
      repo:
        type: string
      api-key:
        type: string
      username:
        type: string
    steps:
      - run: "echo <<parameters.api-key>> | docker login -u <<parameters.username>> --password-stdin"
      - docker/build:
          path: <<parameters.dir>>
          docker-context: <<parameters.dir>>
          image:  <<parameters.repo>>/<<parameters.image>> 
          tag: <<parameters.tag>>
      - run: "docker push <<parameters.repo>>/<<parameters.image>>:<<parameters.tag>>"
      - docker/build:
          path: <<parameters.dir>>
          docker-context: <<parameters.dir>>
          image:  <<parameters.repo>>/<<parameters.image>> 
          tag: latest
      - run: "docker push <<parameters.repo>>/<<parameters.image>>:latest"

orbs:
  docker: circleci/docker@2.1.2
  go: circleci/go@1.7.1
jobs:
  build-eventual-agent:
    executor: 
      name: go/default
      tag: "1.18"
    steps:
      - checkout
      - run: 
          command: | 
            go mod tidy
            go build -o build/ cmd/eventual-agent/eventual-agent.go

  test-eventual-agent:
    executor: 
      name: go/default
      tag: "1.18"
    steps:
      - checkout
      - run: 
          command: | 
            go mod tidy
            go test -v ./...

  build-and-push-eventual-agent:
    executor: docker/machine
    steps:
      - checkout       
      - docker-build-push:
          image: eventual-agent
          repo: $DOCKER_REPO
          tag: <<pipeline.git.tag>>
          username: $DOCKER_USERNAME
          api-key: $DOCKER_API_TOKEN

workflows:
  docker-eventual-agent:
    when:
      << pipeline.git.tag >>
    jobs: 
      - build-and-push-eventual-agent:
          filters:
            branches:
              only: 
                - /release\/.*/ 
            tags:
              only:
                - /^[0-9]*\.[0-9]*\.[0-9]*$/ # Any semver tag i.e. 1.0.0, 2.5.123 - (No beta tags 1.0.0-beta.0 or prefixes v1.0.0)


  eventual-agent:
    jobs:
      - test-eventual-agent:
          filters:
            branches:
              only: 
                - master
                - /release\/.*/ 

      - build-eventual-agent:
          filters:
            branches:
              only: 
                - master
                - /release\/.*/
          requires:
            - test-eventual-agent
